Fix re issue in Python3.6
...
File "/usr/lib/python3.6/sre_parse.py", line 401, in _escape
raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \i at position 28
...
Thx to: 
@MasterOdin - reported the issue
@mizumm - suggested to use 'import regex as re' instead of 'import re' (this should work!); but as long as possible it's preferred not to use third-party add-ons ...